In [3]:
import numpy as np

In [4]:
# 1D Array
a = np.array([1, 2, 3])
print("1D Array:", a)

1D Array: [1 2 3]


In [5]:
# 2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", b)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [6]:
# Zeros, Ones, Empty, Full
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 3)))
print("Empty:\n", np.empty((2, 2)))
print("Full:\n", np.full((2, 2), 7))

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Empty:
 [[2.75678135e-315 0.00000000e+000]
 [5.88193383e-062 1.93410091e-076]]
Full:
 [[7 7]
 [7 7]]


In [7]:
# arange, linspace
print("arange(0, 10, 2):", np.arange(0, 10, 2))
print("linspace(0, 1, 5):", np.linspace(0, 1, 5))

arange(0, 10, 2): [0 2 4 6 8]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [8]:
# Identity and eye
print("Identity Matrix:\n", np.identity(3))
print("Eye (k=1):\n", np.eye(3, k=1))

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Eye (k=1):
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# **Indexing, Slicing, and Shape**

In [9]:
x = np.array([[10, 20, 30], [40, 50, 60]])
print("Original:\n", x)
print("Element x[1,2]:", x[1, 2])
print("First row:", x[0])
print("Second column:", x[:, 1])
print("Sub-array:\n", x[:, 1:3])

Original:
 [[10 20 30]
 [40 50 60]]
Element x[1,2]: 60
First row: [10 20 30]
Second column: [20 50]
Sub-array:
 [[20 30]
 [50 60]]


In [10]:
# Shape and Reshape
print("Shape:", x.shape)
reshaped = x.reshape(3, 2)
print("Reshaped (3x2):\n", reshaped)

# Flatten
print("Flattened:", x.flatten())

# Transpose
print("Transpose:\n", x.T)

Shape: (2, 3)
Reshaped (3x2):
 [[10 20]
 [30 40]
 [50 60]]
Flattened: [10 20 30 40 50 60]
Transpose:
 [[10 40]
 [20 50]
 [30 60]]


# **Mathematical and Statistical Operations**

In [11]:
print("=== Mathematical Operations ===")

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Exponent:", a ** 2)

print("Sum:", np.sum(a))
print("Mean:", np.mean(b))
print("Median:", np.median(b))
print("Standard Deviation:", np.std(b))
print("Variance:", np.var(b))


=== Mathematical Operations ===
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponent: [1 4 9]
Sum: 6
Mean: 5.0
Median: 5.0
Standard Deviation: 0.816496580927726
Variance: 0.6666666666666666


# Boolean Masking and **Comparison**

In [12]:
print("=== Boolean Masking ===")

data = np.array([10, 20, 30, 40])
mask = data > 25
print("Mask:", mask)
print("Filtered:", data[mask])


=== Boolean Masking ===
Mask: [False False  True  True]
Filtered: [30 40]


# **Broadcasting**

In [13]:
print("=== Broadcasting ===")

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([1, 0, 1])
print("Broadcast Addition:\n", x + y)


=== Broadcasting ===
Broadcast Addition:
 [[2 2 4]
 [5 5 7]]


# **Random Numbers**

In [14]:
print("=== Random Generation ===")

np.random.seed(0)
print("Random Integers:\n", np.random.randint(1, 10, (2, 3)))
print("Random Floats:\n", np.random.rand(2, 2))
print("Normal Distribution:\n", np.random.randn(2, 2))


=== Random Generation ===
Random Integers:
 [[6 1 4]
 [4 8 4]]
Random Floats:
 [[0.64589411 0.43758721]
 [0.891773   0.96366276]]
Normal Distribution:
 [[ 1.26611853 -0.50587654]
 [ 2.54520078  1.08081191]]


# **Linear Algebra**

In [15]:
print("=== Linear Algebra ===")

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:\n", np.dot(m1, m2))
print("Determinant:", np.linalg.det(m1))
print("Inverse:\n", np.linalg.inv(m1))
print("Eigenvalues:", np.linalg.eigvals(m1))


=== Linear Algebra ===
Matrix Multiplication:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]


# **Useful Functions**

In [16]:
print("=== Useful NumPy Functions ===")

a = np.array([1, 2, 3])
print("cumsum:", np.cumsum(a))
print("diff:", np.diff(a))
print("clip [min=1, max=2]:", np.clip(a, 1, 2))
print("Unique values:", np.unique([1, 2, 2, 3, 1]))


=== Useful NumPy Functions ===
cumsum: [1 3 6]
diff: [1 1]
clip [min=1, max=2]: [1 2 2]
Unique values: [1 2 3]


# Saving and **Loading**

In [17]:
print("=== Save and Load ===")

arr = np.array([1, 2, 3])
np.save('my_array.npy', arr)
loaded = np.load('my_array.npy')
print("Loaded Array:", loaded)


=== Save and Load ===
Loaded Array: [1 2 3]
