In [2]:
print("Hello NumPy")

Hello NumPy


# **Introduction to NumPy**

In [3]:
import numpy as np

In [4]:
my_list = [1,2,3,4,5]

In [6]:
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

[1 2 3 4 5]


## 1D array

In [8]:
ar1d = np.array([10,20,30,40,50])
print(ar1d)

[10 20 30 40 50]


## 2D Array

In [9]:
ar2d = np.array([[1,2,3],
                 [4,5,6]])
print(ar2d)

[[1 2 3]
 [4 5 6]]


Multidimensional Array

In [13]:
arr3d = np.array([[[1,2,3],[3,4,5]],
                 [[33,55,77],[88,66,44]]])
print(arr3d)

[[[ 1  2  3]
  [ 3  4  5]]

 [[33 55 77]
  [88 66 44]]]


# Array creating:
              Default values/full
              ones
              filled/full

In [14]:
arr0s = np.zeros(3)  #Zeros/default
print(arr0s)

arr1s = np.ones(3)  #ones
print(arr1s)

arrfill = np.full(3, 5) #filled
print(arrfill)

[0. 0. 0.]
[1. 1. 1.]
[5 5 5]


# sequence and identity metrix

In [17]:
arrseq = np.arange(1,11,2)  #sequence
print(arrseq)

arrid = np.eye(3)  #identity
print(arrid)

[1 3 5 7 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# NumPy Array Properties

In [21]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape) #shape of array
print(arr.size) #size of array
print(arr.ndim) #number of dimensions
print(arr.dtype) #type of data stored in array

arr2 = np.array([1.1, 2.3, 4.5])
print(arr2.dtype)
int_Arry = arr2.astype(int)  #converting data from one type to another type
print(int_Arry.dtype)

(2, 4)
8
2
int64
float64
int64


# Mathematical operations

In [23]:
arrmath = np.array([10,20,30,40,50])
print(arrmath + 5)
print(arrmath - 5)
print(arrmath * 5)
print(arrmath / 5)
print(arrmath % 5)
print(arrmath ** 5)

[15 25 35 45 55]
[ 5 15 25 35 45]
[ 50 100 150 200 250]
[ 2.  4.  6.  8. 10.]
[0 0 0 0 0]
[   100000   3200000  24300000 102400000 312500000]


# Aggregations **functions**

In [24]:
arragre = ([1, 2, 3, 4, 5, 55, 1.2, 40])
print(np.sum(arragre))  #total sum of all elements
print(np.min(arragre))  #minimum of all elements
print(np.max(arragre))  #maximum of all elements
print(np.mean(arragre)) #mean of all elements
print(np.median(arragre))  #median of all elements

111.2
1.0
55.0
13.9
3.5


# slicing

In [27]:
arrSlice = ([2,3,4,5, 77, 44, 22])
print(arrSlice[4]) #indexing
print(arrSlice[-5]) #negative indexing
print(arrSlice[::3])
print(arrSlice[2:5]) #slicing

77
77
[4, 5, 77]


# Manipulations

In [29]:
arr3 = np.array([1, 2, 3, 4, 5, 6])
print(arr3)

# Reshaping into 2 rows and 3 columns
reshaped = arr3.reshape(2, 3)  # This returns a view if possible
print(reshaped)

# Creating a 2D array
arrflat = np.array([[2, 3, 4, 5, 6], [7, 8, 1, 9, 0]])

# Using ravel() - returns a flattened view (if possible)
print(arrflat.ravel())

# Using flatten() - returns a flattened copy
print(arrflat.flatten())


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[2 3 4 5 6 7 8 1 9 0]
[2 3 4 5 6 7 8 1 9 0]


# Modifications

In [36]:
arrmodi = np.array([2,3,4,5,6,7,8])
arrmodi1 = np.insert(arrmodi, 5, 44)
print(arrmodi1)

twoDarr = np.array([[1,2,3],[4,5,6]])
print(twoDarr)
insertintwoD = np.insert(twoDarr, 1, 10, axis=1)
print(insertintwoD)
insertintwoD = np.insert(twoDarr, 1, [3,5], axis=1)
print(insertintwoD)

arr4 = np.array([[1,2,3],[4,5,6]])
arr5 = np.array([[7,8,9],[10,11,12]])

print(np.concatenate((arr4, arr5), axis=1))

[ 2  3  4  5  6 44  7  8]
[[1 2 3]
 [4 5 6]]
[[ 1 10  2  3]
 [ 4 10  5  6]]
[[1 3 2 3]
 [4 5 5 6]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [37]:
## Using np.split()
arrsplit = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Original array:", arrsplit)

# Split into 4 equal parts
split_equal = np.split(arrsplit, 4)
print("Split into 4 equal parts:", split_equal)

# Split at specific indices
split_indices = np.split(arrsplit, [2, 5])
print("Split at indices [2, 5]:", split_indices)

print("-" * 20)

## Using np.array_split()
print("## Using np.array_split()")
arrsplit_uneven = np.array([1, 2, 3, 4, 5, 6, 7])
print("Original array:", arrsplit_uneven)

# Split into 3 parts (uneven)
split_uneven = np.array_split(arrsplit_uneven, 3)
print("Split into 3 parts (uneven):", split_uneven)

print("-" * 20)

## Using np.hsplit() (for 2D arrays)
print("## Using np.hsplit() (for 2D arrays)")
two_d_array_h = np.array([[1, 2, 3, 4],
                          [5, 6, 7, 8],
                          [9, 10, 11, 12]])
print("Original 2D array:\n", two_d_array_h)

# Split horizontally into 2 equal parts
hsplit_equal = np.hsplit(two_d_array_h, 2)
print("Horizontal split into 2 equal parts:", hsplit_equal)

# Split horizontally at specific indices
hsplit_indices = np.hsplit(two_d_array_h, [1, 3])
print("Horizontal split at indices [1, 3]:", hsplit_indices)


print("-" * 20)

## Using np.vsplit() (for 2D arrays)
print("## Using np.vsplit() (for 2D arrays)")
two_d_array_v = np.array([[1, 2, 3, 4],
                          [5, 6, 7, 8],
                          [9, 10, 11, 12]])
print("Original 2D array:\n", two_d_array_v)

# Split vertically into 3 equal parts
vsplit_equal = np.vsplit(two_d_array_v, 3)
print("Vertical split into 3 equal parts:", vsplit_equal)

# Split vertically at specific indices
vsplit_indices = np.vsplit(two_d_array_v, [1, 2])
print("Vertical split at indices [1, 2]:", vsplit_indices)

Original array: [1 2 3 4 5 6 7 8]
Split into 4 equal parts: [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
Split at indices [2, 5]: [array([1, 2]), array([3, 4, 5]), array([6, 7, 8])]
--------------------
## Using np.array_split()
Original array: [1 2 3 4 5 6 7]
Split into 3 parts (uneven): [array([1, 2, 3]), array([4, 5]), array([6, 7])]
--------------------
## Using np.hsplit() (for 2D arrays)
Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Horizontal split into 2 equal parts: [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
Horizontal split at indices [1, 3]: [array([[1],
       [5],
       [9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]]), array([[ 4],
       [ 8],
       [12]])]
--------------------
## Using np.vsplit() (for 2D arrays)
Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Vertical split into 3 equal parts: [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), ar

# BroadCasting and Vectorizing

In [42]:
arr55 = np.array([100,200,400,300])

result = arr55 * 2
print(result)

oneD = np.array([2, 3, 5])
TwoD = np.array([[22,33,44],[99,66,55]])
matrix = oneD + TwoD
print(matrix)

[200 400 800 600]
[[ 24  36  49]
 [101  69  60]]


In [44]:
# Vectorization

list1 = np.array([1, 2, 3])
list2 = np.array([4, 5, 6])

resultarr = list1 + list2
print(resultarr)

[5 7 9]


# Handling Missing Values

In [50]:
num = np.array([1, 2, np.nan, 44, 55, np.nan])#nan values

print(np.isnan(num))

cleaned_Arr = np.nan_to_num(num) #changing nan values np.nan_to_num(arr, nan=100) if you wont give 100 then it will take 0 as default value
print(cleaned_Arr)

numarr = np.array([1,2,3, np.inf, 44, 55, -np.inf]) #infinity values
print(numarr)
clean_Arr = np.nan_to_num(numarr, posinf=1000, neginf=-1000) #changing infinity values
print(clean_Arr)

[False False  True False False  True]
[ 1.  2.  0. 44. 55.  0.]
[  1.   2.   3.  inf  44.  55. -inf]
[    1.     2.     3.  1000.    44.    55. -1000.]
